name: JB
title: Record electric guitar on PC
description: An easy guide for home recording
remote_theme: KomunikacjaTechnicznaVistula/just-the-docs

color_scheme: test_jbuk

#logo: "/assets/images/vumeter1.png"

aux_links:
  "Source repository on GitHub":
    - "//github.com/KomunikacjaTechnicznaVistula/jakub-buksinski"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "This documentation is part of the reference materials for the Technical Communication course at Vistula University (Warsaw). The content is based on <a href=\"https://github.com/flicstar/DITA-Mini-Manual\">Felicity Brand's example DITA project.</a>"